services:
  - type: web
    name: msakin
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne msakin.asgi:application -b 0.0.0.0 -p $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: msakin_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REDIS_URL
        fromService:
          name: msakin-redis
          type: redis
          property: connectionString

  - type: redis
    name: msakin-redis
    ipAllowList: []
    plan: free

databases:
  - name: msakin_db
    databaseName: msakin
    plan: free
